name: SonarCloud Analysis
permissions:
  contents: read
  pull-requests: write
on:
  pull_request:
    branches:
      - main
jobs:
  build:
    name: Build and Analyze
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0  # Needed for SonarCloud history
      
      - name: Set up Node.js
        uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af # v4.1.0
        with:
          node-version: '18'
      
      - name: Install dependencies
        run: npm ci
      
      # Optional: Run tests (if you have a test script in package.json)
      - name: Run tests
        run: npm test --if-present
      
      - name: Cache SonarCloud packages
        uses: actions/cache@6849a6489940f00c2f30c0fb92c6274307ccb58a # v4.1.2
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
      
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@383f7e52eae3ab0510c3cb0e7d9d150bbaeab838 # v3.1.0
        with:
          args: >
            -Dsonar.organization=Daniel434m
            -Dsonar.projectKey=Daniel434m_GC_System
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}